kind: Deployment
apiVersion: apps/v1
metadata:
    name: xyztechnologies-dep
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: xyz-tech-app
    template:
        metadata:
            labels:
                app: xyz-tech-app
        spec:
            containers:
                - image: salvathshaik/xyztechnologies
                  name: app
---

kind: Service
apiVersion: v1
metadata:
    name: xyz-tech-service
spec:
    type: NodePort
    selector:
        app: xyz-tech-app
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port
